version: '3'
services:
  db:
    image: mysql:5.6.50
    command: mysqld --character-set-server=utf8
    environment:
      MYSQL_DATABASE: tutor_match_development
      MYSQL_ROOT_PASSWORD: <%= D_MYSQL_PASSWORD %>
      MYSQL_USER: <%= D_MYSQL_USER %>
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myproject/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/myproject
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=<%= D_MYSQL_PASSWORD %>
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
